library(dplyr)
library(lubridate)

hps_data <- read.table("household_power_consumption.txt", sep = ";", header = TRUE, na.strings = "?")
hps_data$Global_active_power= as.numeric(as.character(hps_data$Global_active_power))
hps_data$Global_reactive_power= as.numeric(as.character(hps_data$Global_reactive_power))
hps_data$Voltage= as.numeric(as.character(hps_data$Voltage))
hps_data$Sub_metering_1= as.numeric(as.character(hps_data$Sub_metering_1))
hps_data$Sub_metering_2= as.numeric(as.character(hps_data$Sub_metering_2))
hps_data$Sub_metering_3= as.numeric(as.character(hps_data$Sub_metering_3))
hps_data_filt <- hps_data %>%
  filter(Date == "1/2/2007" | Date =="2/2/2007")
all_data <- hps_data_filt %>%
  mutate(Datetime = paste(Date, Time, sep= " "))
all_data$Datetime = dmy_hms(all_data$Datetime)
png(file = "plot4.png", width = 480, height = 480, units =  "px")
par(mfrow = c(2,2))
plot(all_data$Datetime, all_data$Global_active_power, type= "l", ylab= "Global Active Power (kilowatts)", xlab = "")
plot(all_data$Datetime, all_data$Voltage, type= "l", ylab= "Voltage", xlab = "datetime")
plot(all_data$Datetime, all_data$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
lines(all_data$Datetime, all_data$Sub_metering_2, col="red")
lines(all_data$Datetime, all_data$Sub_metering_3, col="blue")
legend("topright", lty = 1, bty = "n", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red" , "blue"))
plot(all_data$Datetime, all_data$Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power")
dev.off()